### ISSUE TITLE
Security Issue - Protecting Contract from receiving Tokens

### ISSUE THREAD

**Issue by oxdog** [superfluid-finance/super-examples#12]
TBH it is not a bad security issue. I just wanted to point out that this function does not protect the contract from receiving tokens from someone else since anyone can send tokens via their Metamask to the contract bypassing the revert

https://github.com/superfluid-finance/super-examples/blob/82e0af0d855d23ce7993f849a77b1204c8a90a5a/examples/money-streaming-intro/contracts/MoneyRouter.sol#L72

**Comment by ngmachado** [comment]
@oxdog thank you for pointing this out.

@saflamini @sunnyjaycer ,  does make sense trying to block transfer of tokens to the app?

**Comment by JoshuaTrujillo15** [comment]
@oxdog Since ERC20 transfers do not trigger callbacks, there is no way to actually block tokens from being sent to the contract.

This guard is specifically for the functionality of `sendLumpSumToContract`, which is still disallowed.
