### ISSUE TITLE
[DOCUMENTATION]: IDA Readme out of date

### ISSUE THREAD

**Issue by j0xhn** [superfluid-finance/super-examples#36]
### Description

Hi, first of all awesome repo!  Thanks for the great getting started experience.  As I've been going through things, there are just a few issues such as links from the youtube not going to active pages, deployment arguments supplying 2 when the contract calls for 1, file names missing an "s" during console instructions referencing file `scripts/transferInSpreaderToken.js` is really `scripts/transferInSpreaderTokens.js`, and all the scripts not outputting how is expected on georli.  Local works as expected and test suite working as expected, am assuming the script files in the examples must have been updated and just documentation wasn't updated to match? 🤷🏼 

Can provide more info as needed, just wanted to alert the team incase they know what I'm talking about and is an easy documentation/code sync update.

### Components

- [ ] Smart Contracts
- [x] Backend Infrastructure
- [X] Frontend Web Interface

**Comment by sunnyjaycer** [comment]
Hey @j0xhn, thank you for bringing this to our attention! You're right, we switched out to a newer syntax and forgot to update the README walkthrough. Will patch that up today.

**Comment by sunnyjaycer** [comment]
Resolved in #37 ✅
