### ISSUE TITLE
[SUPER-EXAMPLES] Add invariance tests to superApps that use Foundry

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/super-examples#47]

**Comment by vmichalik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/super-examples/47?planning-poker) with Zenhub @0xdavinchee @d10r @ngmachado @philipandersson
