### ISSUE TITLE
[New Example] GDA Super Example: Advertisement Auction

### ISSUE THREAD

**Issue by youssefea** [superfluid-finance/super-examples#58]
**Summary:**

Develop a decentralized application (DApp) using the Superfluid Protocol's General Distribution Agreement (GDA) to facilitate an advertisement auctioning system. The DApp should allow for continuous streams of funds into a pool, distributing half of the incoming funds to the DApp's initial owner and the other half among former advertisers based on the duration of their advertisements. A real-time auction mechanism should enable the highest current contributor to gain advertising rights on the DApp.

**Goals:**

- Implement a GDA-based pool for fund distribution.
- Enable proportional distribution of funds based on advertising time.
- Create a streaming mechanism for funds that allows for real-time auctioning of advertising space.

**Description:**

_Pool Creation and Admin Setup:_

- Develop functionality for any user to create a pool with a specified admin.
- The admin should not be able to assign and revoke units to pool members.
- Stream receivers can trade their shares.

_Fund Distribution Logic:_

- Implement the logic where 50% of incoming streams are sent to the DApp's initial owner.
- The remaining 50% should be distributed among previous advertisers proportionally, based on the amount of time they advertised.

_Advertisement Auctioning Mechanism:_

- Integrate a bidding system where advertisers can create a stream to the pool.
- The advertiser with the highest current stream should automatically gain the right to advertise on the DApp.
- Upon being outbid, the previous highest stream is stopped and the user gets proportionate shares for future distributions.

_Share Allocation Based on Advertisement Time:_

- Ensure that shares are allocated to advertisers corresponding to how long their advertisement was displayed.
- Shares determine the proportion of the 50% fund distribution received by previous advertisers.

_DApp Interface:_

- Design and develop a user-friendly interface for the auctioning system.
- Display current advertisement, the highest stream, the advertiser's info, and time advertised.

_Smart Contract Development:_

- Write and test smart contracts to handle stream creation, share assignment, fund distribution, and real-time auctioning.

_Security and Testing:_

- Thoroughly test the smart contracts for bug/vulnerabilities and ensure robust handling of funds and shares.
- Set up contracts on testnets verify functionality.

**Acceptance Criteria:**

- A fully functional GDA-based DApp allowing for the advertisement auctioning as described.
- An intuitive UI/UX that allows users to easily participate in the auctioning process and view pertinent information.
- Complete documentation detailing the DApp's functionality, smart contract interactions, and user instructions.

**Nice to have:**

- The DApp should be scalable to accommodate a growing number of advertisers and increased fund flows.
- The DApp should be aligned with the latest industry standards (Account abstraction, security practices etc.).
- Consider gas optimization for transactions to enhance user experience.
- The DApp should comply with all relevant regulations of the DeFi and advertising space.

**Comment by philipandersson** [comment]
How do we distribute? How can we make builders/developers excited about this?
