### ISSUE TITLE
Pleaser ressurect the hot-fuzz integration using code from previous example project in monorepo 

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/super-examples#9]
### Description

See: https://github.com/superfluid-finance/protocol-monorepo/blob/d93b1a743ead8000544596b8565f7a93eea42943/examples/tradeable-cashflow/tradeable-cashflow-truffle/package.json#L19

### Components

- [x] Smart Contracts
- [ ] Backend Infrastructure
- [ ] Frontend Web Interface

**Comment by JoshuaTrujillo15** [comment]
A ticket is in the backlog, but the team currently does not have the resources to add more to this repository.

Please submit a pull request with the suggested changes.

**Comment by jtriley2p** [comment]
gg
